rmi.host=localhost
rmi.registry.port=1099
rmi.service.port=1100

rmi.service.equipo=EquipoService
rmi.service.tecnico=TecnicoService
rmi.service.orden=OrdenService
rmi.service.auth=AuthService

rmi.ssl.enabled=false
rmi.keystore.path=localhost
rmi.keystore.password=sigomei123
rmi.truststore.path=config/client.jks
rmi.truststore.password=sigomei123

db.url=jdbc:mysql://localhost:3306/sigomei_db?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
db.user=sigomei
db.password=sigomei123
db.driver=com.mysql.cj.jdbc.Driver
